export default [
  { 
    title: '布丁準備',
    coverImage: './assets/cover/pudding-cake.gif',
    coverStyle: 'round',
    backgroundColor: '#feebed',
    clockColor: '#644329',
    scheduleMessageColor: '#785c47',
    noteMessageColor: '#b89168',
    rolloutColor: 'brown',
  },
  { 
    title: '課間下課',
    coverImage: './assets/cover/ai-jamming.gif',    
    coverStyle: 'round',
    backgroundColor: '#f8eee3',
    clockColor: '#574E72',
    scheduleMessageColor: '#26375E',
    noteMessageColor: '#684848',
    rolloutColor: 'blue',
  },
  { 
    title: '隨堂測驗',
    coverImage: './assets/cover/sisi-phone.png',    
    coverStyle: 'square',
    backgroundColor: '#f2eeed',
    clockColor: '#877179',
    scheduleMessageColor: '#a39eac',
    noteMessageColor: '#535253',
    rolloutColor: 'grey',
  },
  { 
    title: '電腦測驗',
    coverImage: './assets/cover/sisi-computer.png',    
    coverStyle: 'square',
    backgroundColor: '#f2eeed',
    clockColor: '#877179',
    scheduleMessageColor: '#a39eac',
    noteMessageColor: '#535253',
    rolloutColor: 'grey',
  },
  { 
    title: '討論協力',
    coverImage: './assets/cover/sisi-pair-work.png',
    coverStyle: 'square',
    backgroundColor: '#C4E6C7',
    clockColor: '#404344',
    scheduleMessageColor: '#a39eac',
    noteMessageColor: '#8c7e80',
    rolloutColor: 'grey',
  },
  { 
    title: '討論交流',
    coverImage: './assets/cover/sisi-pair-talk.png',
    coverStyle: 'square',
    backgroundColor: '#C4E6C7',
    clockColor: '#404344',
    scheduleMessageColor: '#a39eac',
    noteMessageColor: '#8c7e80',
    rolloutColor: 'grey',
  },
  { 
    title: '比賽中',
    coverImage: './assets/cover/sisi-tournament.png',
    coverStyle: 'square',
    backgroundColor: '#f2cba7',
    clockColor: '#767D1B',
    scheduleMessageColor: '#852122',
    noteMessageColor: '#a66c44',
    rolloutColor: 'brown',
  },
]